### ISSUE TITLE
Components without styles being loaded in on load after upgrade to version 3.0.1

### ISSUE THREAD

**Issue by jwrlee88** [jaredpalmer/after.js#329]
### Current Behavior
Hello, I'm in the midst of upgrading my After.JS project to Version 3.0.1. I've followed the [migration guide.md pretty much down to a T](https://github.com/jaredpalmer/after.js/blob/master/UPGRADING.md) and I'm still seeing the behaviour from before the upgrade, which is when you first load the app, or you hard refresh the page, the page flashes a version of the app without the styles being loaded in. 

Please see the attached gif to see what I mean. 

![scribr](https://user-images.githubusercontent.com/39804005/80619238-6e222f80-8a12-11ea-8c8a-f91c627e831d.gif)

### Expected behavior
I expected that, after #232 and #237 was merged, the behaviour shown above in the gif would not happen. 

Under the Additional Context section I have attached the 4 major files that were changed during this upgrade via following the guide. This is either a bug or a user error, if it is a user error, I'm not sure what I'm doing wrong. Any guidance here would be much appreicated.

### Additional context
Just like the upgrading guide suggested, these are my client.js, server.js, 
document.js, and routes.js file. 

Client.JS: 
```
import React from 'react'
import { hydrate } from 'react-dom'
import { BrowserRouter } from 'react-router-dom'
import { ensureReady, After, getSerializedData } from '@jaredpalmer/after';
import { Provider } from 'react-redux'
import configureStore from './redux/configureStore'
import './font-awesome'
import routes from './routes'
import './client.scss'
import AppContainer from './AppContainer'

const preloadedState = getSerializedData('preloaded_state');
const store = configureStore(preloadedState)

const App = ({ data }) => (
  <BrowserRouter>
    <Provider store={store}>
      <>
        <After data={data} routes={routes} store={store}/>
        <AppContainer/>
      </>
    </Provider>
  </BrowserRouter>
)

function renderApp () {
  ensureReady(routes).then(data =>
    hydrate(
      <App data={data}/>,
      document.getElementById('root')
    )
  )
}

renderApp()

if (module.hot) {
  module.hot.accept('./routes', renderApp)
}

```

Document.JS: 
```
import React from 'react'
import { Provider } from 'react-redux';
import serialize from 'serialize-javascript';
import { runtimeConfig } from './runtimeConfig'
import {
  AfterRoot,
  AfterData,
  AfterScripts,
  AfterStyles,
  SerializeData,
  __AfterContext
} from '@jaredpalmer/after';

class Document extends React.Component {

  static async getInitialProps (initialProps) {
    const { renderPage, store } = initialProps

    const page = await renderPage(App => props => (
      <Provider store={store}>
        <App {...props} />
      </Provider>
    ))

    return { ...page }
  }

  render () {
    const { helmet } = this.props

    const htmlAttrs = helmet.htmlAttributes.toComponent()
    const bodyAttrs = helmet.bodyAttributes.toComponent()

    return (
      <html {...htmlAttrs}>
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta charSet="utf-8"/>
        <title>Scribr.FM</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/>
        {helmet.title.toComponent()}
        {helmet.meta.toComponent()}
        {helmet.link.toComponent()}
        <AfterStyles />
        <script dangerouslySetInnerHTML={{
          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-ID-HERE');`
        }}>
        </script>
      </head>
      <body {...bodyAttrs}>
        <AfterRoot/>
        <AfterData />
        <ReduxData/>
        <AfterScripts />
        <LoadEnvVars/>
        <noscript dangerouslySetInnerHTML={{
          __html:
              `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-ID-HERE"
                              height="0" width="0" style="display:none;visibility:hidden">
                </iframe>`
        }}>
        </noscript>
      </body>
      </html>
    )
  }
}

function LoadEnvVars() {
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `window.env = ${serialize(runtimeConfig)}`,
      }}
    />
  )
}

function ReduxData() {
  const { store } = React.useContext(__AfterContext);
  return <SerializeData name="preloaded_state" data={store.getState()} />;
}

export default Document
```

Server.JS: 

```
import express from 'express';
import { render } from '@jaredpalmer/after';
import routes from './routes';
import Document from './document';
import configureStore from "./redux/configureStore";

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST);
const chunks = require(process.env.RAZZLE_CHUNKS_MANIFEST);

for (const key of Object.keys(chunks)) {
  if(chunks[key].js) {
    chunks[key].js = chunks[key].js.filter(f => f.slice(-4) !== '.map');
  }
}

const server = express();
server
  .disable('x-powered-by')
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR))
  .get('/*', async (req, res) => {
    try {

      const store = configureStore();

      const html = await render({
        req,
        res,
        routes,
        assets,
        chunks,
        document: Document,
        // Anything else you add here will be made available
        // within getInitialProps(ctx)
        // e.g a redux store...
        store,
      });
      res.send(html);
    } catch (error) {
      console.error(error);
      res.json({ message: error.message, stack: error.stack });
    }
  });

export default server;

```

Routes.JS: 
```
import React from 'react';

import { asyncComponent } from '@jaredpalmer/after';
import LoadingIndicator from "./components/LoadingIndicator";

export default [
  {
    path: '/browse',
    exact: true,
    component: asyncComponent({
      loader: () => import(/* webpackChunkName: "Browse" */ './containers/Browse/_Browse'),
      chunkName: 'Browse'
    })
  }
  {
    path: '/',
    exact: true,
    component: asyncComponent({
      loader: () => import(/* webpackChunkName: "Home" */'./containers/Home/_Home'), // required
      chunkName: 'Home',
      Placeholder: () => <LoadingIndicator/>
    }),
  },
  {
    path: '/subscriptions',
    exact: true,
    component: asyncComponent({
      loader: () => import(/* webpackChunkName: "Subscriptions" */ './containers/Subscriptions/_Subscriptions'),
      chunkName: 'Subscriptions'
    })
  },
  {
    path: '/favorites',
    exact: true,
    component: asyncComponent({
      loader: () => import(/* webpackChunkName: "Favorites" */ './containers/Favorites/Favorites'),
      chunkName: 'Favorites'
    })
  },
  {
    path: '',
    exact: true,
    component: asyncComponent({
      loader: () => import(/* webpackChunkName: "404" */'./containers/404/404'),
      chunkName: '404'
    })
  }
];

```

my package.json file, but please see `Your environment` section for a TLDR: 

```
{
  "name": "razzle-examples-with-afterjs",
  "version": "3.0.0",
  "license": "MIT",
  "scripts": {
    "start": "razzle start",
    "build": "razzle build",
    "test": "razzle test --env=jsdom",
    "start:prod": "NODE_ENV=production node build/server.js",
    "json-server": "node json-server/server.js"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-regular-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/react-fontawesome": "^0.1.7",
    "@jaredpalmer/after": "^3.0.1",
    "@juggle/resize-observer": "^3.0.2",
    "afterjs-assets": "^1.0.1",
    "bootstrap": "^4.3.1",
    "connected-react-router": "^6.5.2",
    "dotenv": "^8.2.0",
    "express": "^4.16.2",
    "express-form-data": "^2.0.10",
    "history": "^4.10.1",
    "hoist-non-react-statics": "^3.3.0",
    "immutable": "^4.0.0-rc.12",
    "invariant": "^2.2.4",
    "isomorphic-unfetch": "^3.0.0",
    "json-server": "^0.15.1",
    "lodash": "^4.17.15",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.24.0",
    "path": "^0.12.7",
    "prop-types": "^15.7.2",
    "query-string": "^6.8.3",
    "razzle": "^3.1.0",
    "react": "^16.10.2",
    "react-albus": "^2.0.0",
    "react-audio-player": "^0.11.1",
    "react-autosize-textarea": "^7.0.0",
    "react-contenteditable": "^3.3.2",
    "react-dom": "^16.10.2",
    "react-facebook-login": "^4.1.1",
    "react-google-login": "^5.1.1",
    "react-helmet": "^6.0.0",
    "react-highlight-words": "^0.16.0",
    "react-hot-loader": "^4.12.15",
    "react-loader-spinner": "^3.1.5",
    "react-moment": "^0.9.6",
    "react-multi-carousel": "^2.4.2",
    "react-physics-dragger": "^1.3.2",
    "react-redux": "^7.1.1",
    "react-responsive": "^8.0.1",
    "react-router-dom": "^4.2.2",
    "react-slick": "^0.25.2",
    "react-slidedown": "^2.4.4",
    "react-spring": "^8.0.27",
    "react-tagsinput": "^3.19.0",
    "react-toastify": "^5.4.1",
    "react-use-gesture": "^7.0.1",
    "reactstrap": "^8.1.1",
    "redux": "^4.0.4",
    "redux-immutable": "^4.0.0",
    "redux-saga": "^1.1.1",
    "reselect": "^4.0.0",
    "resize-observer-polyfill": "^1.5.1",
    "sass-mq": "^5.0.1",
    "seamless-immutable": "^7.1.4",
    "serialize-javascript": "^2.1.0",
    "slate": "^0.47.8",
    "slate-react": "^0.22.9",
    "slick-carousel": "^1.8.1",
    "slugify": "^1.3.6",
    "styled-components": "^4.4.1",
    "uniqid": "^5.0.3",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "razzle-plugin-scss": "^3.0.0"
  }
}

```

### Your environment

We're also running this in Docker, but here are the specs: 

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | ^16.10.2
| After.js         | ^3.0.1
| Razzle           | ^ 3.1.0
| Razzle Plugins   | N/A
| TypeScript       | N/A
| Node             | 11.4
| Browser          | Google Chrome
| npm/Yarn         | 1.12.3
| Operating System | Bionic Beaver Xubuntu 18.04

**Comment by nimaa77** [comment]
hello
why you wrote your routes like that? if you add the babel plugin there is no need to add /* chunkName */ and other stuff

and about CSS:
on development mode not even one CSS file is created and they created in run time and injected to the HTML by webpack (this is how webpack works...

so if you run `npm run build` or `yarn build` and then you start the server in production mode (`yarn start:prod` or `npm run start:prod`)
everything should work without any problems

**Comment by jwrlee88** [comment]
Hi, I initially wrote it like that to follow the upgrading guide. 

I took your advice and added a `.babelrc` and reverted my routes file to what it was previously. I also added the `babel-plugin-after` package as well. 

.babelrc: 
```
{
  "presets": [ "razzle/babel" ],
  "plugins": [ "after" ]
}
```
I ran `yarn build` and then `yarn start:prod` afterwards, and I got a bunch of these errors: 

```
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
scribr_react-ws                     |  - options has an unknown property 'minimize'. These properties are valid:
scribr_react-ws                     |    object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
scribr_react-ws                     |  @ ./src/components/PodcastCard/PodcastCard.js 2:0-28
scribr_react-ws                     |  @ ./src/components/DraggableCarousel/DraggableCarousel.js
scribr_react-ws                     |  @ ./src/containers/Home/Home.js
scribr_react-ws                     |  @ ./src/components/HomeAudioPlayer/HomeTimer/HomeTimer.js
scribr_react-ws                     |  @ ./src/components/HomeAudioPlayer/HomeAudioPlayer.js
scribr_react-ws                     |  @ ./src/AppContainer.js
scribr_react-ws                     |  @ ./src/client.js

```
It works fine in normal dev mode, just when I try to build it, i get this error. Am I missing something? 

Thank you for your help, I really appreciate it.

**Comment by jwrlee88** [comment]
After further investigation, I have found that this is a known issue in Razzle, and there is a pending [PR already](https://github.com/jaredpalmer/razzle/pull/1274). 

I'm also using the `razzle-scss-plugin` in my project, and that issue in the previous comment has happened after I upgraded Razzle, which means my issue will be solved once you guys solve the issue with the breaking change with CSS-Loader and Razzle-Scss-Plugin. 

Thank you @nimaa77 for your contribution and hard work around Razzle and After.js, I'll keep an eye on things to see how you guys are doing in a few.

**Comment by nimaa77** [comment]
thanks, I will close this issue let's move conversations about the webpack tooling (I mean razzle) to it's repo

**Comment by nimaa77** [comment]
@jee1mr heyy, scss isuue fixed in new version of razzle and razzle-plugin-scss (`v3.1.1`)

**Comment by mghazanfar** [comment]
> @jee1mr heyy, scss issue fixed in the new version of `razzle` and `razzle-plugin-scss` (`v3.1.1`)

@nimaa77 First of all, I had to struggle hard to find which version of razzle was compatible with razzle-plugin-scss v3.1.1 to fix it, as it was not mentioned.
Latest of all version does not work for my app's code and keeps throwing webpack not found exception. I finally got 3.4.5 working with my current apps' code, my app is built with 3.0.0 though.
So the issue is still there and it is giving me FOUC on initial render. Extremely upset as have spent so much time on it.
